#--------------------------------------------------------------------------------
#
#    ,--.              ,--.         ,---.         ,---.              ,--. 
#    |  | ,---.  ,---. |  |,-.     |  o ,-.      /  .-' ,---.  ,---. |  | 
#    |  || .-. || .-. ||     /     .'     /_     |  `-,| .-. :| .-. :|  | 
#    |  |' '-' '' '-' '|  \  \     |  o  .__)    |  .-'\   --.\   --.|  | 
#    `--' `---'  `---' `--'`--'     `---'        `--'   `----' `----'`--' 
#                                                                         
#           _______
#　　　　　 /  ＞　　フ     
#　　　　　| 　_　 _ l      RESUME: Visual config & animations to make
#　 　　　／` ミ＿xノ               beautiful components
#　　 　 /　　　 　 |
#　　　 /　 ヽ　　 ﾉ
#　 　 │　　|　|　|         AUTHOR:  Andr3xDev
#　／￣|　　 |　|　|        URL: https://github.com/Andr3xDev/HyprPharch
#　| (￣ヽ＿_ヽ_)__)
#　＼二つ
#--------------------------------------------------------------------------------


#--- Import colors ---#
source = ~/.config/hypr/theme/colors.conf


#--------------------------------------------------------------------------------
# Gaps, borders, layouts & configs
#--------------------------------------------------------------------------------
general {
    gaps_in = 4
    gaps_out = 8

    border_size = 2

    col.active_border = $border_active
    col.inactive_border = $border_inactive

    resize_on_border = false
    allow_tearing = true
    layout = master
}


#--------------------------------------------------------------------------------
# Blur, shadow & more
#--------------------------------------------------------------------------------
decoration {
    rounding = 6
    active_opacity = 1
    inactive_opacity = $opacity
    dim_special = 0.5

    shadow {
        enabled = true
        range = 20
        render_power = 2
        color = rgba(11111b70)
        color_inactive = rgba(00000000)
    }

    blur {
        enabled = true
        size = 3
        passes = 3
        ignore_opacity = false 
        new_optimizations = true
        special = false
        popups = true
    }
}


#--------------------------------------------------------------------------------
# Animations for everything
#--------------------------------------------------------------------------------

animations {
    enabled = true

    #--- Beziers custom ---#
    bezier = elegantOut, 0.23, 1, 0.32, 1
    bezier = elegantIn, 0.4, 0, 0.2, 1

    #--- Custom animations ---#
    # workspaces
    animation = workspaces, 1, 5, elegantOut, slide
    animation = specialWorkspace, 1, 5, elegantOut, fade

    # windows
    animation = windows, 1, 4, elegantOut, popin 85%
    animation = windowsIn, 1, 4, elegantOut, popin 85%
    animation = windowsOut, 1, 2, elegantIn, popin 85%
    animation = windowsMove, 1, 5, elegantOut, slide

    # Layers & menus
    animation = layersIn, 1, 4, elegantOut, fade
    animation = layersOut, 1, 4, elegantIn, fade
    animation = fade, 1, 4, elegantOut

    # borders
    animation = border, 1, 2, elegantOut
    animation = borderangle, 0
}
