-- Generated by hyprmonitor
-- Last updated: 2026-06-08T20:50:28
-- Do not edit manually — use the hyprmonitor GUI or create monitors.lua to override

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@60.018",
    position = "-1640x-153",
    scale    = 1.25,
})

hl.monitor({
    output   = "DP-1",
    mode     = "1920x1080@74.973",
    position = "-104x-120",
    scale    = 1.0,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1280x720@60",
    position = "1816x143",
    scale    = 0.83,
})

-- Fallback: any unrecognized monitor gets best available mode
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1.0,
})
