import QtQuick

/*!
    LuaSerializer — Strategy pattern (pure JS, no side effects).

    Transforms a LuaDocument into the Lua string written by FileWriter.
    Intercambiable without touching MonitorConfigBuilder or FileWriter.

    Output format: hl.monitor({ ... }) blocks, field names aligned to 9 chars.
*/
QtObject {
    id: root

    function serialize(doc) {
        const timestamp = new Date().toISOString().slice(0, 19)
        const lines = [
            "-- Generated by hyprmonitor",
            `-- Last updated: ${timestamp}`,
            "-- Do not edit manually — use the hyprmonitor GUI or create monitors.lua to override",
            ""
        ]

        for (const entry of doc.entries) {
            if (entry.output === "") {
                lines.push("-- Fallback: any unrecognized monitor gets best available mode")
            }

            lines.push("hl.monitor({")
            lines.push(`    ${"output".padEnd(9)}= "${entry.output}",`)

            if (entry.disabled) {
                lines.push(`    ${"mode".padEnd(9)}= "disabled",`)
            } else {
                lines.push(`    ${"mode".padEnd(9)}= "${entry.mode}",`)
                lines.push(`    ${"position".padEnd(9)}= "${entry.position}",`)
                lines.push(`    ${"scale".padEnd(9)}= ${_formatScale(entry.scale)},`)
                if (entry.transform !== null && entry.transform !== undefined) {
                    lines.push(`    ${"transform".padEnd(9)}= ${entry.transform},`)
                }
            }

            lines.push("})")
            lines.push("")
        }

        return lines.join("\n")
    }

    // Ensures floats always have a decimal point
    function _formatScale(scale) {
        return Number.isInteger(scale) ? scale + ".0" : String(scale)
    }
}
