# Abysal Obsidian

$base    = rgb(1c1c1c) # main_background
$surface = rgb(262626) # secondary_background
$text    = rgb(d4d4d4) # main_text

$color1 = rgb(52c9b0) # turquoise
$color2 = rgb(e28e5a) # orange
$color3 = rgb(d1b171) # sand
$color4 = rgb(d47779) # soft_red
$color5 = rgb(6b92e3) # steel_blue
$color6 = rgb(b87bce) # lavender_purple
$color7 = rgb(8c8c8c) # light_gray_secondary
$color8 = rgb(737373) # medium_gray_comments
$color9 = rgb(2e2e2e) # dark_gray_borders

# Highlight colors
$highlight1 = rgb(2a2a2a) # faint_selection
$highlight2 = rgb(333333) # medium_selection
$highlight3 = rgb(454545) # strong_selection

$wallpaper = ~/.config/wallpapers/frieren-1.png

# Border configuration
$border_active   = $highlight3 # Gray focus (Highlight 3)
$border_inactive = $color9     # Darker gray borders
$border_urgent   = $color4     # Soft Red

$opacity = 0.95

# Hyprlock Specifics
$lock_background_brightness = 0.8

$lock_text          = $text
$lock_shadow        = $base

$lock_time_hours    = $color1
$lock_time_minutes  = $color3
$lock_time_date     = $color2

$lock_input_bg      = $surface
$lock_input_border  = $color1
$lock_input_text    = $text

$lock_actions_bg    = $surface
$lock_actions_border = $color1
$lock_actions_text  = $text

$lock_battery_bg    = $surface
$lock_battery_border = $color1
$lock_battery_text  = $text
