# Abysal Marble

$base    = rgb(dcdcdc) # main_background
$surface = rgb(cfcfcf) # secondary_background
$text    = rgb(2f2f2f) # main_text

$color1 = rgb(2c9279) # turquoise
$color2 = rgb(b55b25) # orange
$color3 = rgb(947635) # sand
$color4 = rgb(a8474a) # soft_red
$color5 = rgb(365ca8) # steel_blue
$color6 = rgb(824699) # lavender_purple
$color7 = rgb(555555) # dark_gray_secondary
$color8 = rgb(737373) # medium_gray_comments
$color9 = rgb(bcbcbc) # light_gray_borders

# Highlight colors
$highlight1 = rgb(d4d4d4) # faint_selection
$highlight2 = rgb(c4c4c4) # medium_selection
$highlight3 = rgb(b8b8b8) # strong_selection

$wallpaper = ~/.config/wallpapers/wall_CR.jpg

# Border configuration
$border_active   = $highlight3 # Muted gray focus
$border_inactive = $color9     # Soft light gray
$border_urgent   = $color4     # Deep Red

$opacity = 0.92

# Hyprlock Specifics
$lock_background_brightness = 0.9

$lock_text          = $text
$lock_shadow        = $base

$lock_time_hours    = $color1
$lock_time_minutes  = $color2
$lock_time_date     = $color3

$lock_input_bg      = $surface
$lock_input_border  = $color1
$lock_input_text    = $text

$lock_actions_bg    = $surface
$lock_actions_border = $color1
$lock_actions_text  = $text

$lock_battery_bg    = $surface
$lock_battery_border = $color1
$lock_battery_text  = $text
