-- Generated by hyprmonitor
-- Last updated: 2026-05-24T08:35:45
-- Do not edit manually — use the hyprmonitor GUI or create monitors.lua to override

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@144.002",
    position = "-1536x0",
    scale    = 1.25,
})

hl.monitor({
    output   = "DP-1",
    mode     = "1920x1080@74.973",
    position = "0x0",
    scale    = 1.0,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1280x720@60",
    position = "1933x-23",
    scale    = 1.0,
})

-- Fallback: any unrecognized monitor gets best available mode
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1.0,
})
