#--------------------------------------------------------------------------------
#             _______
#　　　　　 /  ＞　　フ     
#　　　　　| 　_　 _ l      THEME: abysal-obsidian
#　 　　　／` ミ＿xノ               
#　　 　 /　　　 　 |
#　　　 /　 ヽ　　 ﾉ
#　 　 │　　|　|　|         AUTHOR:  Andr3xDev
#　／￣|　　 |　|　|        URL: https://github.com/Andr3xDev/HyprPharch
#　| (￣ヽ＿_ヽ_)__)
#　＼二つ
#   
#--------------------------------------------------------------------------------


[app]
overall = { bg = "#dcdcdc" }

[mgr]
cwd = { fg = "#2c9279" }

find_keyword = { fg = "#2c9279", bold = true, italic = true, underline = true }
find_position = { fg = "#824699", bg = "reset", bold = true, italic = true }

symlink_target = { italic = true }

marker_copied = { fg = "#365ca8", bg = "#365ca8" }
marker_cut = { fg = "#a8474a", bg = "#a8474a" }
marker_marked = { fg = "#a04e1e", bg = "#a04e1e" }
marker_selected = { fg = "#7a6020", bg = "#7a6020" }

count_copied = { fg = "#dcdcdc", bg = "#365ca8" }
count_cut = { fg = "#dcdcdc", bg = "#a8474a" }
count_selected = { fg = "#dcdcdc", bg = "#2c9279" }

border_symbol = "│"
border_style = { fg = "#bcbcbc" }

syntect_theme = ""

[indicator]
padding = { open = "█", close = "█" }
parent  = { fg = "#dcdcdc", bg = "#737373" }
current = { fg = "#dcdcdc", bg = "#2c9279" }
preview = { fg = "#dcdcdc", bg = "#737373" }

[tabs]
active = { fg = "#dcdcdc", bg = "#2c9279", bold = true }
inactive = { fg = "#555555", bg = "#bcbcbc" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "█", close = "" }

[mode]
normal_main = { fg = "#dcdcdc", bg = "#2c9279", bold = true }
normal_alt = { fg = "#2f2f2f", bg = "#c4c4c4", bold = true }

select_main = { fg = "#dcdcdc", bg = "#7a6020", bold = true }
select_alt = { fg = "#2f2f2f", bg = "#c4c4c4", bold = true }

unset_main = { fg = "#dcdcdc", bg = "#a8474a", bold = true }
unset_alt = { fg = "#2f2f2f", bg = "#c4c4c4", bold = true }

[status]
overall = { bg = "#dcdcdc" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

perm_sep = { fg = "#737373" }
perm_type = { fg = "#824699" }
perm_read = { fg = "#2c9279" }
perm_write = { fg = "#a8474a" }
perm_exec = { fg = "#a04e1e" }

progress_label = { fg = "#2f2f2f", bold = true }
progress_normal = { fg = "#2c9279", bg = "#dcdcdc" }
progress_error = { fg = "#a8474a", bg = "#dcdcdc" }

[which]
cols = 3
mask = { bg = "#dcdcdc" }
cand = { fg = "#2c9279" }
rest = { fg = "#737373" }
desc = { fg = "#a04e1e" }
separator = "  "
separator_style = { fg = "#737373" }

[confirm]
border = { fg = "#2c9279" }
title = { fg = "#a8474a", bold = true }
body = { fg = "#2f2f2f" }
list = { fg = "#2f2f2f" }
btn_yes = { fg = "#dcdcdc", bg = "#2c9279", bold = true }
btn_no = { fg = "#2f2f2f", bg = "#c4c4c4", bold = true }
btn_labels = ["  [y]es  ", "  (n)o  "]

[spot]
border = { fg = "#2c9279" }
title = { fg = "#2c9279", bold = true }

tbl_col = { fg = "#2c9279" }
tbl_cell = { fg = "#dcdcdc", bg = "#2c9279", bold = true }

[notify]
title_info = { fg = "#2c9279" }
title_warn = { fg = "#7a6020" }
title_error = { fg = "#a8474a" }

[pick]
border = { fg = "#2c9279" }
active = { fg = "#2c9279", bold = true }
inactive = { fg = "#555555" }

[input]
border = { fg = "#2c9279" }
title = { fg = "#2c9279", bold = true }
value = { fg = "#2f2f2f" }
selected = { reversed = true }

[cmp]
border = { fg = "#2c9279" }
active = { bg = "#c4c4c4", fg = "#2c9279", bold = true }
inactive = { fg = "#555555" }

[tasks]
border = { fg = "#2c9279" }
title = { fg = "#2c9279", bold = true }
hovered = { fg = "#2f2f2f", bg = "#2c9279", bold = true }

[help]
on = { fg = "#2c9279" }
run = { fg = "#a04e1e" }
desc = { fg = "#7a6020" }
hovered = { fg = "#2f2f2f", bg = "#2c9279", bold = true }
footer = { fg = "#2f2f2f", bg = "#c4c4c4" }

[filetype]
rules = [
  { mime = "image/*", fg = "#365ca8" },
  { mime = "{audio,video}/*", fg = "#a04e1e" },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#a8474a" },
  { mime = "application/{pdf,doc,rtf}", fg = "#7a6020" },
  { mime = "application/vnd.oasis.opendocument.*", fg = "#7a6020" },
  { mime = "application/vnd.openxmlformats-officedocument.*", fg = "#7a6020" },

  { url = "*", is = "orphan", fg = "#dcdcdc", bg = "#a8474a" },
  { url = "*", is = "exec", fg = "#365ca8" },
  { url = "*", is = "dummy", fg = "#dcdcdc", bg = "#a8474a" },
  { url = "*/", is = "dummy", fg = "#dcdcdc", bg = "#a8474a" },

  { url = "*/", fg = "#2f2f2f" },

  { url = "*", fg = "#2f2f2f" },
]
