#--------------------------------------------------------------------------------
#
#                           ,------.                          ,--.   
#                           |  .-.  \ ,--.,--.,--,--,  ,---.,-'  '-. 
#                           |  |  \  :|  ||  ||      \(  .-''-.  .-' 
#                           |  '--'  /'  ''  '|  ||  |.-'  `) |  |   
#                           `-------'  `----' `--''--'`----'  `--'   
#           _______
#　　　　　 /  ＞　　フ     
#　　　　　| 　_　 _ l      RESUME: General config to full notifications
#　 　　　／` ミ＿xノ       
#　　 　 /　　　 　 |       THEME: abysal-marble
#　　　 /　 ヽ　　 ﾉ
#　 　 │　　|　|　|         AUTHOR: Andr3xDev
#　／￣|　　 |　|　|        URL: https://github.com/Andr3xDev/HyprPharch
#　| (￣ヽ＿_ヽ_)__)
#　＼二つ
#--------------------------------------------------------------------------------


[global]
    format = "<b>%s %p</b>\n%b"
    sort = yes
    indicate_hidden = true
    idle_threshold = 0
    width = 300
    alignment = center
    show_age_threshold = 40
    sticky_history = yes
    word_wrap = yes
    separator_height = 2
    horizontal_padding = 10
    follow = mouse
    frame_width = 3
    corner_radius = 8
    offset = (20,20)
    separator_color = "#bcbcbc"

[urgency_low]
    background = "#dcdcdc"
    foreground = "#2f2f2f"
    frame_color = "#bcbcbc"
    timeout = 7
    format = "<b><span color='#947635'>%s</span></b>\n%b"

[urgency_normal]
    background = "#dcdcdc"
    foreground = "#2f2f2f"
    frame_color = "#bcbcbc"
    timeout = 7
    format = "<b><span color='#2c9279'>%s</span></b>\n%b"

[urgency_critical]
    background = "#dcdcdc"
    foreground = "#2f2f2f"
    frame_color = "#a8474a"
    highlight = "#a8474a"
    timeout = 10
    format = "<b><span color='#a8474a'>%s</span></b>\n%b"
